-- 코드를 입력하세요
-- SELECT  BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, REPLY.CREATE_DATE FROM USED_GOODS_BOARD BOARD, USED_GOODS_REPLY REPLY WHERE BOARD.BOARD_ID=REPLY.BOARD_ID AND BOARD.CREATE_DATE = ''

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') FROM USED_GOODS_BOARD B INNER JOIN USED_GOODS_REPLY R ON R.BOARD_ID=B.BOARD_ID WHERE B.CREATED_DATE BETWEEN TO_DATE('2022-10-01','YYYY-MM-DD') AND TO_DATE('2022-10-31','YYYY-MM-DD') ORDER BY R.CREATED_DATE, B.TITLE;

